package:
    name: openjpeg
    version: 2.1.0

source:
    fn: version.2.1.tar.gz
    url: https://github.com/uclouvain/openjpeg/archive/version.2.1.tar.gz
    md5: 3e1c451c087f8462955426da38aa3b3d

build:
    number: 2
    skip: True  # [win and py35]
    features:
        - vc9  # [win and py27]
        - vc10  # [win and py34]
        - vc14  # [win and py35]

requirements:
    build:
        - python  # [win]
        - cmake
        - libtiff
        - libpng
        - zlib
    run:
        - libtiff
        - libpng
        - zlib

test:
    requires:
        # Avoids
        # """Error: The following specifications were found to be in conflict:
        # - udunits2 2.2.20 vc9_1"""
        - python {{ environ['PY_VER'] + '*' }}  # [win]
    files:
        - p0_01.j2k
    commands:
        - opj_dump -i p0_01.j2k
        - conda inspect linkages -n _test openjpeg  # [linux]

about:
    home: http://www.openjpeg.org/
    license: BSD 2-clauses
    summary: An open-source JPEG 2000 codec written in C

extra:
  recipe-maintainers:
    - ocefpaf
    - gillins
